version: "2"

run:
  timeout: 5m
  allow-parallel-runners: true
  go: '1.23'

linters:
  default: none
  enable:
    - dupl
    - errcheck
    - copyloopvar
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - gosec
    - bodyclose
    - whitespace
    - nilerr
  settings:
    revive:
      rules:
        - name: comment-spacings
    gocyclo:
      min-complexity: 20
    gosec:
      excludes:
        - G104
  exclusions:
    presets: []
    rules:
      - path: "api/*"
        linters:
          - lll
      - path: "internal/*"
        linters:
          - dupl
          - lll
      - path: zz_generated\.
        linters:
          - revive
          - gocritic
      - path: cmd/main\.go
        linters:
          - gocyclo
          - revive
        text: "cyclomatic|cognitive"
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - gosec

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    paths:
      - zz_generated\.

