# This rule is not used by the project homelab-alm itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to networking.alm.homelab resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: homelab-alm
    app.kubernetes.io/managed-by: kustomize
  name: certificaterequest-viewer-role
rules:
- apiGroups:
  - networking.alm.homelab
  resources:
  - certificaterequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.alm.homelab
  resources:
  - certificaterequests/status
  verbs:
  - get
