# This rule is not used by the project homelab-alm itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the networking.my.domain.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: homelab-alm
    app.kubernetes.io/managed-by: kustomize
  name: ingressrequest-editor-role
rules:
- apiGroups:
  - networking.my.domain
  resources:
  - ingressrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.my.domain
  resources:
  - ingressrequests/status
  verbs:
  - get
