name: Cleanup Docker Images 

on:
  workflow_dispatch:
  schedule: # Run weekly
    - cron: '0 0 * * 0'  # 00:00 UTC

jobs:
  prune:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package-type: 'container'
          package-name: 'homelab-alm'
          min-versions-to-keep: 9